sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t sklyushin2018/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sklyushin2018/docker-react npm run test
